name: Build SneedWolf on Linux

on:
  workflow_dispatch:
    inputs:
      debugger_keyword:
        description: "Name of the debugger keyword"
        required: false
        type: string
        default: ""

  workflow_call:
    inputs:
      debugger_keyword:
        description: "Name of the debugger keyword"
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Free up Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force

      - name: Get librewolf source....
        working-directory: ./
        run: git clone --recursive "https://sneedgit.nodemixaholic.com/Sneed-Group/sneedwolf-source" librewolf
      
      - name: Bootstrap Source and de-brand
        continue-on-error: true
        working-directory: ./librewolf
        run: make bootstrap

      - name: debrand and hacky linux fix
        continue-on-error: true
        working-directory: ./librewolf
        run: |
          cp -rf l10n librewolf*/lw
          rm -rf librewolf*/browser/branding/librewolf
          cd librewolf*
          cp -rf browser/branding/unofficial browser/branding/librewolf
          mkdir -p obj-x86_64-pc-linux-gnu/.mozbuild/
          touch obj-x86_64-pc-linux-gnu/.mozbuild/profile_build_resources.json
          cd ..
        
      - name: Set Release Tag Output
        id: release-tag
        run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Construct New `debugger` Keyword
        id: debugger-keyword
        run: echo "DEBUGGER_KEYWORD=${{ inputs.debugger_keyword || format('debugger{0}', steps.release-tag.outputs.NOW) }}" >> "$GITHUB_OUTPUT"

      - name: Replace `debugger` Keyword
        working-directory: ./librewolf
        run: sed -i'' -e 's/MACRO(debugger/MACRO(${{ steps.debugger-keyword.outputs.DEBUGGER_KEYWORD }}/' ./librewolf*/js/src/frontend/ReservedWords.h
      
      - name: Build
        working-directory: ./librewolf
        run: |
          cd librewolf*
          ./mach build
          cd ..
          
      - name: Box it up
        working-directory: ./librewolf
        run: |
          cd librewolf*
          ./mach package
          cd ..
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-firefox-artifacts
          path: "./librewolf/librewolf*/obj-x86_64-pc-linux-gnu/dist/*.tar*"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./librewolf/librewolf*/obj-x86_64-pc-linux-gnu/dist/*.tar*"
          tag: linux-${{ steps.release-tag.outputs.NOW }}
