name: Build

on:
  workflow_dispatch:

# env:

jobs:
  build-reggubed-firefox:
    runs-on: windows-latest
    steps:
      - name: Install Mozilla Build
        run: "choco install mozillabuild -y"
      - name: Open Mozilla Build Shell
        shell: C:\mozilla-build\start-shell.bat -e {0}
        run: |
          cd d:/
          ls -la
