name: Build SneedWolf on All Platforms

on:
  repository_dispatch:
    types: [firefox-source-code-update]

  workflow_dispatch:
    inputs:
      debugger_keyword:
        description: "Name of the debugger keyword"
        required: false
        type: string
        default: ""

permissions:
  contents: write

jobs:
  build-on-linux:
    uses: ./.github/workflows/build-on-linux.yml
    with:
      debugger_keyword: ${{ inputs.debugger_keyword }}
  build-on-macos:
    uses: ./.github/workflows/build-on-macos.yml
    with:
      debugger_keyword: ${{ inputs.debugger_keyword }}
