name: Build SneedWolf on macOS

on:
  workflow_dispatch:
    inputs:
      debugger_keyword:
        description: "Name of the debugger keyword"
        required: false
        type: string
        default: ""

  workflow_call:
    inputs:
      debugger_keyword:
        description: "Name of the debugger keyword"
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Install Mercurial
        run: python3 -m pip install --break-system-packages -U mercurial

      - name: Get librewolf patches....
        working-directory: ./
        run: git clone "https://codeberg.org/librewolf/source" librewolf

      - name: Install and cache Homebrew GPG GCC MAKE CMAKE RUST and WASI
        # You may pin to the exact commit or the version.
        # uses: gerlero/brew-install@678576f264550d4179d266e23e206c54b8623864
        uses: gerlero/brew-install@v1.1.0
        with:
          # Formulae or casks to install
          packages: gpg gcc make cmake wasi-libc rust
          # Cache the downloaded packages
          cache: false # optional, default is true
          # The type of packages to install (formula or cask)
          type: formula # optional, default is any
          

      - name: Bootstrap Source and de-brand
        working-directory: ./librewolf
        run: |
          make bootstrap
          cp -r l10n librewolf*/lw
          rm -rf browser/branding/librewolf
          cp browser/branding/unofficial browser/branding/librewolf
        
      - name: Set Release Tag Output
        id: release-tag
        run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Construct New `debugger` Keyword
        id: debugger-keyword
        run: echo "DEBUGGER_KEYWORD=${{ inputs.debugger_keyword || format('debugger{0}', steps.release-tag.outputs.NOW) }}" >> "$GITHUB_OUTPUT"

      - name: Replace `debugger` Keyword
        working-directory: ./librewolf
        run: sed -i'' -e 's/MACRO(debugger/MACRO(${{ steps.debugger-keyword.outputs.DEBUGGER_KEYWORD }}/' ./librewolf*/js/src/frontend/ReservedWords.h
      
      - name: Build
        working-directory: ./librewolf
        run: make build
          
      - name: Box it up
        working-directory: ./librewolf
        run: make package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-firefox-artifacts
          path: "./librewolf/librewolf*/*apple-darwin*/dist/librewolf*.mac.dmg"
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./librewolf/librewolf*/*apple-darwin*/dist/librewolf*.mac.dmg"
          tag: macos-${{ steps.release-tag.outputs.NOW }}
