name: Build

on:
  workflow_dispatch:

# env:

jobs:
  build-reggubed-firefox:
    runs-on: windows-latest
    steps:
      - name: Download Mozilla Build
        run: "curl -o mozilla-build.exe -L https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe"
      - name: Install Mozilla Build
        shell: cmd
        run: "mozilla-build.exe /S /D=.\\mozilla-build"
      - name: Open Mozilla Build Shell
        shell: cmd
        run: |
          call ".\mozilla-build\start-shell.bat"
          mkdir mozilla-source
          cd mozilla-source
          wget https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py
          python3 bootstrap.py
